[package]
name = "bevy_world_to_screenspace"
version = "0.1.0"
authors = ["Aevyrie Roessler <aevyrie@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "18e4fa8" }
#bevy_fly_camera = "0.6.0"